# Under Sampling

## "no_relation"

In [65]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold

import seaborn as sns
import matplotlib.pyplot as plt
import random

df = pd.read_csv('data/train.csv')
df.head()

,id,sentence,subject_entity,object_entity,label,source
0,0,〈Something〉는 조지 해리슨이 쓰고 비틀즈가 1969년 앨범 《Abbey R...,"{'word': '비틀즈', 'start_idx': 24, 'end_idx': 26...","{'word': '조지 해리슨', 'start_idx': 13, 'end_idx':...",no_relation,wikipedia
1,1,호남이 기반인 바른미래당·대안신당·민주평화당이 우여곡절 끝에 합당해 민생당(가칭)으...,"{'word': '민주평화당', 'start_idx': 19, 'end_idx': ...","{'word': '대안신당', 'start_idx': 14, 'end_idx': 1...",no_relation,wikitree
2,2,K리그2에서 성적 1위를 달리고 있는 광주FC는 지난 26일 한국프로축구연맹으로부터...,"{'word': '광주FC', 'start_idx': 21, 'end_idx': 2...","{'word': '한국프로축구연맹', 'start_idx': 34, 'end_idx...",org:member_of,wikitree
3,3,균일가 생활용품점 (주)아성다이소(대표 박정부)는 코로나19 바이러스로 어려움을 겪...,"{'word': '아성다이소', 'start_idx': 13, 'end_idx': ...","{'word': '박정부', 'start_idx': 22, 'end_idx': 24...",org:top_members/employees,wikitree
4,4,1967년 프로 야구 드래프트 1순위로 요미우리 자이언츠에게 입단하면서 등번호는 8...,"{'word': '요미우리 자이언츠', 'start_idx': 22, 'end_id...","{'word': '1967', 'start_idx': 0, 'end_idx': 3,...",no_relation,wikipedia

In [45]:
df['label'].value_counts()

no_relation                            9534
org:top_members/employees              4284
per:employee_of                        3573
per:title                              2103
org:member_of                          1866
org:alternate_names                    1320
per:origin                             1234
org:place_of_headquarters              1195
per:date_of_birth                      1130
per:alternate_names                    1001
per:spouse                              795
per:colleagues                          534
per:parents                             520
org:founded                             450
org:members                             420
per:date_of_death                       418
org:product                             380
per:children                            304
per:place_of_residence                  193
per:other_family                        190
per:place_of_birth                      166
org:founded_by                          155
per:product                             139
per:siblings                            136
org:political/religious_affiliation      98
per:religion                             96
per:schools_attended                     82
org:dissolved                            66
org:number_of_employees/members          48
per:place_of_death                       40
Name: label, dtype: int64

In [66]:
# idx = random.sample(list(df.loc[df['label']=='no_relation'].id), int(9534/2))
# df.drop(idx, axis=0)['label'].value_counts()

idx = random.sample(list(df.loc[df['label']=='no_relation'].id), int(9534/2))
df_us = df.drop(idx, axis=0)
df_us

,id,sentence,subject_entity,object_entity,label,source
0,0,〈Something〉는 조지 해리슨이 쓰고 비틀즈가 1969년 앨범 《Abbey R...,"{'word': '비틀즈', 'start_idx': 24, 'end_idx': 26...","{'word': '조지 해리슨', 'start_idx': 13, 'end_idx':...",no_relation,wikipedia
1,1,호남이 기반인 바른미래당·대안신당·민주평화당이 우여곡절 끝에 합당해 민생당(가칭)으...,"{'word': '민주평화당', 'start_idx': 19, 'end_idx': ...","{'word': '대안신당', 'start_idx': 14, 'end_idx': 1...",no_relation,wikitree
2,2,K리그2에서 성적 1위를 달리고 있는 광주FC는 지난 26일 한국프로축구연맹으로부터...,"{'word': '광주FC', 'start_idx': 21, 'end_idx': 2...","{'word': '한국프로축구연맹', 'start_idx': 34, 'end_idx...",org:member_of,wikitree
3,3,균일가 생활용품점 (주)아성다이소(대표 박정부)는 코로나19 바이러스로 어려움을 겪...,"{'word': '아성다이소', 'start_idx': 13, 'end_idx': ...","{'word': '박정부', 'start_idx': 22, 'end_idx': 24...",org:top_members/employees,wikitree
5,5,": 유엔, 유럽 의회, 북대서양 조약 기구 (NATO), 국제이주기구, 세계 보건 ...","{'word': '북대서양 조약 기구', 'start_idx': 13, 'end_i...","{'word': 'NATO', 'start_idx': 25, 'end_idx': 2...",org:alternate_names,wikipedia
...,...,...,...,...,...,...
32465,32465,한국당은 7일 오전 9시부터 오후 5시까지 진행된 원내대표 및 정책위의장 후보자 등...,"{'word': '유기준', 'start_idx': 93, 'end_idx': 95...","{'word': '부산 서구·동구', 'start_idx': 100, 'end_id...",per:employee_of,wikitree
32466,32466,"법포는 다시 최시형, 서병학, 손병희 직계인 북접과 다시 서장옥, 전봉준, 김개남을...","{'word': '최시형', 'start_idx': 7, 'end_idx': 9, ...","{'word': '손병희', 'start_idx': 17, 'end_idx': 19...",per:colleagues,wikipedia
32467,32467,완도군(군수 신우철)이 국토교통부에서 실시한 '2019 교통문화지수 실태조사'에서 ...,"{'word': '완도군', 'start_idx': 0, 'end_idx': 2, ...","{'word': '신우철', 'start_idx': 7, 'end_idx': 9, ...",org:top_members/employees,wikitree
32468,32468,"중앙일보, JTBC 회장을 지낸 이후 중앙홀딩스 회장, 재단법인 한반도평화만들기 이...","{'word': 'JTBC', 'start_idx': 6, 'end_idx': 9,...","{'word': '중앙홀딩스', 'start_idx': 21, 'end_idx': ...",no_relation,wikipedia
32469,32469,화순군(군수 구충곤)은 17일 동면의 이장 20여 명이 코로나 19 예방을 위해 버...,"{'word': '화순군', 'start_idx': 0, 'end_idx': 2, ...","{'word': '구충곤', 'start_idx': 7, 'end_idx': 9, ...",org:top_members/employees,wikitree

In [68]:
df_us.to_csv('/Users/youp/Desktop/df_half_no-relation.csv', encoding="utf-8-sig", index=False)

# Over Sampling

## up to 2000

In [3]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
# import random
from numpy import random

df = pd.read_csv('data/train.csv')
df.head()
df['label'].value_counts()

no_relation                            9534
org:top_members/employees              4284
per:employee_of                        3573
per:title                              2103
org:member_of                          1866
org:alternate_names                    1320
per:origin                             1234
org:place_of_headquarters              1195
per:date_of_birth                      1130
per:alternate_names                    1001
per:spouse                              795
per:colleagues                          534
per:parents                             520
org:founded                             450
org:members                             420
per:date_of_death                       418
org:product                             380
per:children                            304
per:place_of_residence                  193
per:other_family                        190
per:place_of_birth                      166
org:founded_by                          155
per:product                             139
per:siblings                            136
org:political/religious_affiliation      98
per:religion                             96
per:schools_attended                     82
org:dissolved                            66
org:number_of_employees/members          48
per:place_of_death                       40
Name: label, dtype: int64

In [4]:
df_over = df
label_dist = df['label'].value_counts()

# over sampling
np.random.seed(42)
for label in df['label'].unique():
    if label_dist[label] <= 2000:    # elif 추가로 기존 개수에 따라 차등 복사 가능
        idx = random.choice(list(df.loc[df['label']==label].id), int(2000-label_dist[label])) # 2000개가 되도록 복사
        df_over = pd.concat([df_over, df.iloc[idx, :]], axis = 0)
print(df_over.shape)
        
# shuffling data
df_over = df_over.sample(frac=1)  # row 전체 shuffle
df_over = df_over.sample(frac=1).reset_index(drop=True)  # shuffling하고 index reset
df_over

(71494, 6)

,id,sentence,subject_entity,object_entity,label,source
0,12752,2012년 10월 18일 만화가 미티는 네이버의 앱 홍보용 릴레이 웹툰 ‘앱피소드(...,"{'word': '정다정', 'start_idx': 88, 'end_idx': 90...","{'word': '웹툰 《역전! 야매요리》', 'start_idx': 63, 'en...",per:product,wikipedia
1,9541,1987년 대선 당시 김대중이 평화민주당을 창당하면서 젊은피 수혈이라는 정책을 펴서...,"{'word': '평화민주당', 'start_idx': 17, 'end_idx': ...","{'word': '김대중', 'start_idx': 12, 'end_idx': 14...",org:founded_by,wikipedia
2,15630,"2009년 9월 19일, 그의 네번째 분데스리가 경기인 FC 바이에른 뮌헨 원정 경...","{'word': '분데스리가', 'start_idx': 21, 'end_idx': ...","{'word': 'FC 바이에른 뮌헨', 'start_idx': 31, 'end_i...",org:members,wikipedia
3,13758,대회 공식 후원사인 현대자동차도 선수 및 관계자 수송에 제네시스 차량 70여대를 투...,"{'word': '현대자동차', 'start_idx': 11, 'end_idx': ...","{'word': '제네시스', 'start_idx': 31, 'end_idx': 3...",org:product,wikitree
4,23438,대한민국 임시 의정원은 대한민국 임시정부의 입법부 기능을 수행하였다.,"{'word': '대한민국 임시정부', 'start_idx': 13, 'end_id...","{'word': '임시 의정원', 'start_idx': 5, 'end_idx': ...",org:members,wikipedia
...,...,...,...,...,...,...
71489,19418,배우 김우빈(31·김현중)이 연인 신민아(36·양민아) 소속사로 옮겼다.,"{'word': '김우빈', 'start_idx': 3, 'end_idx': 5, ...","{'word': '김현중', 'start_idx': 10, 'end_idx': 12...",per:alternate_names,wikitree
71490,590,일본의 진언종은 구카이(空海くうかい홍법 대사: 774-835)가 중국 당나라의 장안...,"{'word': '구카이', 'start_idx': 9, 'end_idx': 11,...","{'word': '진언종', 'start_idx': 4, 'end_idx': 6, ...",per:religion,wikipedia
71491,1961,그러나 마우리키우스가 재정난 해결을 위해 아바르족이 잡아간 포로들의 몸값을 지불하지...,"{'word': '포카스', 'start_idx': 88, 'end_idx': 90...","{'word': '마우리키우스', 'start_idx': 98, 'end_idx':...",no_relation,wikipedia
71492,23957,이기훈 연구원은 “CJ ENM은 CJ헬로 매각으로 확보한 현금을 바탕으로 스튜디오드...,"{'word': '스튜디오드래곤', 'start_idx': 41, 'end_idx'...","{'word': 'ENM', 'start_idx': 13, 'end_idx': 15...",no_relation,wikitree
71493,1394,"봉은사, 월정사 등에서 행자 생활을 거쳐 2016년 직지사에서 사미계를 받으면서 대...","{'word': '직지사', 'start_idx': 29, 'end_idx': 31...","{'word': '대한불교 조계종', 'start_idx': 45, 'end_idx...",org:political/religious_affiliation,wikipedia

In [34]:
df_over.to_csv('/Users/youp/Desktop/train_oversampling2000.csv', encoding="utf-8-sig", index=False)

In [5]:
df_over['label'].value_counts()

no_relation                            9534
org:top_members/employees              4284
per:employee_of                        3573
per:title                              2103
per:parents                            2000
per:religion                           2000
org:alternate_names                    2000
per:schools_attended                   2000
per:siblings                           2000
org:dissolved                          2000
org:political/religious_affiliation    2000
per:other_family                       2000
org:number_of_employees/members        2000
org:founded                            2000
per:spouse                             2000
per:product                            2000
org:founded_by                         2000
per:date_of_birth                      2000
per:colleagues                         2000
per:place_of_death                     2000
org:member_of                          2000
per:place_of_residence                 2000
per:alternate_names                    2000
per:origin                             2000
org:place_of_headquarters              2000
per:children                           2000
per:date_of_death                      2000
org:product                            2000
org:members                            2000
per:place_of_birth                     2000
Name: label, dtype: int64

In [42]:
a = {0:'a', 1:'b', 2:'c'}
{value:key for key, value in list(a.items())}

{'a': 0, 'b': 1, 'c': 2}

In [45]:
import pickle
with open(f'dict_label_to_num.pkl', 'rb') as f: 
    dict1 = pickle.load(f)
dict1

{'no_relation': 0,
 'org:top_members/employees': 1,
 'org:members': 2,
 'org:product': 3,
 'per:title': 4,
 'org:alternate_names': 5,
 'per:employee_of': 6,
 'org:place_of_headquarters': 7,
 'per:product': 8,
 'org:number_of_employees/members': 9,
 'per:children': 10,
 'per:place_of_residence': 11,
 'per:alternate_names': 12,
 'per:other_family': 13,
 'per:colleagues': 14,
 'per:origin': 15,
 'per:siblings': 16,
 'per:spouse': 17,
 'org:founded': 18,
 'org:political/religious_affiliation': 19,
 'org:member_of': 20,
 'per:parents': 21,
 'org:dissolved': 22,
 'per:schools_attended': 23,
 'per:date_of_death': 24,
 'per:date_of_birth': 25,
 'per:place_of_birth': 26,
 'per:place_of_death': 27,
 'org:founded_by': 28,
 'per:religion': 29}